title: [Luiz Real contribution]
description: [I help professional Java developers build visibility and meaningful relationships in the tech community so they can grow their careers and become highly valued in the industry.]
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: G-TCZNKNLHYV